# Generated by Django 6.0 on 2025-12-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_user_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(help_text='Phone number in format 2547XXXXXXXX', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Daraja CheckoutRequestID from Mpesa', max_length=255, null=True),
        ),
    ]
